## Introduction
To practice some matrix and vector operations in Python, we will use a package called SciPy.  Within this package, there is a subpackage called `scipy.linalg` which builds on the package `NumPY`. We have actually already been using `NumPy` in previous notebooks. 

Let's import these packages.

In [2]:
# run this cell
import numpy as np
import scipy.linalg as la

## NumPy Arrays: What are they?
We can think of 1D (1 Dimensional) NumPy array as a list of numbers (or a vector!). We can also think of a 2D NumPy array as a matrix. And we can think of a 3D array as a cube of numbers (also known as tensor or an image!). 

When we select a row or a column from a 2D NumPy array, the result is a 1D NumPy array. This can get a bit confusing, so it is important to keep track of the shape, size and dimension of our NumPy arrays. 

- To create a 1D NumPy array (or vector) we use the function `np.array([])`, and inside the brackets (`[]`) we input numbers separated by a `,` comma. 

In [3]:
# Run this cell to see this creation in action
# our 1D array is stored in the variable a
a = np.array([1,3,-2,-1])

# let's see how it looks like by printing
print(a)

[ 1  3 -2 -1]


- To verify the dimension of this 1D array or Vector, we use the function `.ndim`. 

In [4]:
# Run this cell

# your_array.ndim
a.ndim

1

- The shape of the 1D array or vector is given by `.shape`

In [5]:
# Run this cell

# your_array.shape
a.shape

(4,)

**Note**: In this case `(4,)` is telling you that there are 4 elements in this vector. You can think of vectors in python written horizontally. 

### Matrices
Let's now create a 2D array (matrix). We will call this matrix `M`.

In [11]:
# Run this cell
M = np.array([[1,2],[-1,4], [6,5]])
print(M)

[[ 1  2]
 [-1  4]
 [ 6  5]]


Note how the syntax (the way we write code) inside the function `np.array` changed from a single set of `[]` brackets, to 2 sets of `[]` brackets inside another set of brackets. Each of the brackets inside stores a list of numbers or vector. 

- Let's check the dimension: this is telling us what kind of `NumPy` array we have. We should now expect a 2D array.

In [12]:
# use .ndim again
M.ndim

2

- Now let's verify the shape.

In [13]:
# use .shape again
M.shape

(3, 2)

- What if we want to know the number of entries inside of the matrix?

In [15]:
# Run this cell
# here we use the function .size
M.size

6

As mentioned before, if we select a column from a 2D `NumPy` array we get a vector or 1D array.

In [16]:
col = M[:,1]
print(col)

[2 4 5]


**Note**
When indexing (putting brackets with colons next to arrays, like `M`) it is important to understand the dimensions of our array.

In this case since M is 2D, we are dealing with a matrix that has **rows** and **columns**. It is important to keep in mind that when indexing, the *left most value* refers to **rows*** and *right most value* refers to **columns**.

`M[row,column]`

these must be separated by a comma.

**Python Indexing**: 
1. When wanting to access (or index) into the first element of an array or list, Python's first element will always be 0. That is, if I were to want to extract the first column instead of the second one as we did above, we will write `0` in place of `1`. Run the cell below to see this in action.
2. Notice how we are not specifying which rows we wish to access. Since we want all the rows from the first column, in the `[row,]` dimension of indexing, we simply type `:`.

In [18]:
first_column = M[:,0]
print(first_column)

[ 1 -1  6]


- What if you just want the first row of the first column (that's just a single value within the matrix)!

In [19]:
single_value = M[0,0]
print(single_value)

1


We can still verify dimensions and shapes with columns.

In [21]:
# run this cell to see it in action
first_column.ndim

1

In [23]:
# run this cell to see the shape
first_column.shape

(3,)

## Matrix  Operations and Functions

Recall the arithmetic operations we discussed in the Python intro notebooks. When dealing with `NumPy` arrays, these arithmetic operations (`+`,`-`,`/`,`*`, and `**`) are performed elementwise on `NumPy` arrays. In other words, the rules you know of vectors and matrices are preserved in Python!

1. Let's create a NumPy array and do some computations.

In [24]:
# Run this cell

# Our matrix is now called M2 
M2 = np.array([[3,4], [-2,6]])
print(M2)

[[ 3  4]
 [-2  6]]


Matrix multiplication in Python is actually performed with the `@` symbol. Notice what happens when we use the `*` instead.

In [25]:
# Run this cell to see what happens.
M2 * M2

array([[ 9, 16],
       [ 4, 36]])

2. Let's now do an actual matrix multiplication.

In [27]:
# Run this cell to see the result
M2 @ M2

array([[  1,  36],
       [-18,  28]])

2. What if we want to compute the following: $2I + 3A - AB$ for 

$$A = \begin{bmatrix}1 & 3 \\-1 & 7 \end{bmatrix}  B = \begin{bmatrix}5 & 2 \\1 & 2 \end{bmatrix}$$

and $I$ is the identity matrix of size 2.

$$I = \begin{bmatrix}1 & 0 \\0 & 1 \end{bmatrix}$$

In [28]:
# Run this cell to create A 
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [29]:
# Run this cell to create B
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


Note that `NumPy` has a function called `np.eye` which creates an Identity matrix $I$ for you of whatever size you wish. In this case, we want to create an identity matrix of size 2.

In [30]:
I = np.eye(2) # the two denotes the size we want
print(I)

[[1. 0.]
 [0. 1.]]


We can now compute what we want!

In [31]:
# Run this cell to see the result

2*I + 3*A -A@B

array([[-3.,  1.],
       [-5., 11.]])

## Matrix Powers
1. Unfortunately there is no symbol for matrix powers and so we must import the function `matrix_power` from the subpackge we talked about `scipy.linalg`.

In [41]:
# lets import it
from numpy.linalg import matrix_power as mpow

In [43]:
# run this cell to redefine M
M = np.array([[3,4], [-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


2. Say we want to raise the matrix `M` to the power of 2.
    - First argument in `mpow`  is your matrix of choice (in this case `M`)
    - Second argument in `mpow` is the power you wish to raise your matrix `M` to (in this case 2)

In [44]:
# run this cell to see it in action
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

3. What if we want to raise it to the power of 5?

In [45]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

Since we are raising a Matrix to a power, it is the same as multiplying `M` by itself 2 (for power of 2) times.

In [46]:
# run this cell to see it in action: we should get the same result as above
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's now do the same for the power of 5.

In [47]:
# Run this cell
M @ M @ M @ M @ M 

array([[-1525,  3236],
       [ -809,    93]])

## Transpose of a Matrix
We can also take the transpose with the attribute/function `.T`.

In [35]:
# Run to recall what the value of the variable M2 was (it was the last matrix we did!)
print(M2)

[[ 3  4]
 [-2  6]]


In [36]:
# Run to transpose
transpose = M2.T
print(transpose)

[[ 3 -2]
 [ 4  6]]


## Inverse of a Matrix

We can find the inverse using the function `la.inv`

In [37]:
# lets create a matrix C 
C = np.array([[1,2],[3,4]])
print(C)

[[1 2]
 [3 4]]


In [39]:
# let's now get its inverse
inv_c = la.inv(C)
print(inv_c)

[[-2.   1. ]
 [ 1.5 -0.5]]


## Exercise
Compute the matrix equation $AB + 2B^2 - I$ for matrices

$$A = \begin{bmatrix}3 & 4 \\-1 & 2 \end{bmatrix}  B = \begin{bmatrix}5 & 2 \\8 & -3 \end{bmatrix} $$.

In [ ]:
# create your matrix A here
A = 

In [ ]:
# create your matrix B here
B = 

In [ ]:
# create your I here
I = np.eye()

In [ ]:
# Calculate here!